In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.style.use(['fivethirtyeight', 'figsize'])
_SAVEDIR_ = 'Tex/figures/'

In [9]:
nx = 100
visco = .1
ar = 0
br = 0
sigma =  5
rho0 = 1
rho_inl = 1.01
rho_out = .99
u0 = .1
efield = 0
Nsteps = 1001
ndiag = 10
iseed = 795325167

In [46]:
w = np.array([2./3,1./6,1./6])
def init(sigma, u0, w, nx,Nsteps):
    x = np.linspace(-nx/(2*sigma),nx/(2*sigma),nx)
    amp = 1/(np.sqrt(2*np.pi)*sigma)
    rho = rho0 + np.exp(-.5*x**2)
    u = np.ones_like(x)*u0
    f = np.zeros([Nsteps,nx,3])
#     f[0,:,0] = rho*w[0]
#     f[0,:,1] = rho*w[1]
#     f[0,:,2] = rho*w[2]
    f[0,:,:] = np.dot(np.expand_dims(rho,axis=1),np.expand_dims(w,axis=0))
    return x, rho, u, f
def hydrovar(rho,u,f,nx, ts):
    rho = np.sum(f[ts,:])
    u = (f[ts,:,1]-f[ts,:,2])/rho
    return rho, u


In [47]:
x, rho, u, f = init(sigma,u0,w,nx,Nsteps)
f[0,:,1]/ f[0,:,0]

array([ 0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,
        0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,
        0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,
        0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,
        0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,
        0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,
        0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,
        0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,
        0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,
        0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,
        0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25,  0.25])

In [30]:
w = np.array([2./3,1./6,1./6])
print(w)
w = np.array([2./3,1./6,1./6])
print(np.expand_dims(w,axis=0))
print(np.expand_dims(w,axis=1).shape)
print(np.expand_dims(rho,axis=0).shape)

[ 0.66666667  0.16666667  0.16666667]
[[ 0.66666667  0.16666667  0.16666667]]
(3, 1)
(1, 100)


In [31]:
np.dot(np.expand_dims(w,axis=1),np.expand_dims(rho,axis=0))

array([[ 0.66666667,  0.66666667,  0.66666667,  0.66666667,  0.66666667,
         0.66666667,  0.66666667,  0.66666667,  0.66666667,  0.66666667,
         0.66666667,  0.66666667,  0.66666667,  0.66666667,  0.66666667,
         0.66666667,  0.66666667,  0.66666667,  0.66666667,  0.66666667,
         0.66666668,  0.66666671,  0.6666668 ,  0.66666707,  0.66666782,
         0.66666986,  0.66667517,  0.66668841,  0.66672004,  0.66679243,
         0.66695114,  0.6672844 ,  0.66795446,  0.66924395,  0.67161836,
         0.67579983,  0.68283868,  0.69415715,  0.71152844,  0.73694895,
         0.77237052,  0.81928661,  0.87821386,  0.94816689,  1.02627167,
         1.10767644,  1.18588043,  1.25350664,  1.30341627,  1.32994098,
         1.32994098,  1.30341627,  1.25350664,  1.18588043,  1.10767644,
         1.02627167,  0.94816689,  0.87821386,  0.81928661,  0.77237052,
         0.73694895,  0.71152844,  0.69415715,  0.68283868,  0.67579983,
         0.67161836,  0.66924395,  0.66795446,  0.6